Broken CMS block preview when using identifier in pagebuilder
magento/magento2-page-builder pull request #812
Opened 2022-06-24 08:07 UTC by rvr-robert

### Description (*)
When adding a CMS block in a CMS page using the block identifier instead of the block ID, pagebuilder displays following error : "Block with ID: [block identifier] doesn't exist." instead of showing preview of the CMS block.

The block renders properly on front-end.
There is no way to add a block with his identifier directly from pagebuilder. This issue would only happen if a developer executes a data patch that generates CMS content or directly edit the content in the database.

### Bug
* [<2838>](https://jira.corp.magento.com/browse/<2838>) Broken CMS block preview when using identifier in pagebuilder

### Fixed Issues (if relevant)
1. magento/magento2#35070: Broken CMS block preview when using identifier in pagebuilder

### Manual testing scenarios (*)

1. Create a CMS Block with any content
2. Create a CMS Page and add previously created CMS Block in the page with the PageBuilder Block component
3. Open cms_page table
4. Find the created page
5. Replace block_id value with the block identifier in the content cell. Example for a block with identifier contact-us-banner :
6. <div data-content-type="block" data-appearance="default" data-element="main">{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="contact-us-banner" type_name="CMS Static Block"}}</div>
7. Apply changes
8. Refresh pagebuilder page to see error

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-06-24 08:13 UTC, rvr-robert commented
@magento run all test

2024-01-10 09:53 UTC, engcom-Hotel commented
@magento run all tests

2024-01-10 12:18 UTC, engcom-Hotel requested changes
Hello @rvr-robert,

Thanks for the collaboration!

Please update the PR branch with the latest changes in the master branch. Then we will pick this PR for review. It seems the failures are due to this only.

Thanks

2024-11-13 07:27 UTC, engcom-Hotel commented
@magento run all tests

2024-11-21 14:12 UTC, engcom-Hotel commented
Hello @rvr-robert @jeremycharron,

Thanks for the contribution!

Can you please help us understand the need to update the database in order to reproduce the issue? I think this is not the correct way to produce an issue. Can we reproduce the issue without this?

Thanks

2024-11-21 14:21 UTC, jeremycharron commented
> Hello @rvr-robert @jeremycharron,
> 
> Thanks for the contribution!
> 
> Can you please help us understand the need to update the database in order to reproduce the issue? I think this is not the correct way to produce an issue. Can we reproduce the issue without this?
> 
> Thanks

Hi @engcom-Hotel 
The real concern would be when you are creating a CMS block and assigning it to a page programmatically (in a data patch for example). You'd want the created page to use the same block identifier on every environment the patch is ran.
Editing the database directly is just a quick way to replicate the issue without writing a fictional data patch.

Thanks

2024-11-22 09:35 UTC, engcom-Hotel commented
@magento run all tests

2024-11-22 11:22 UTC, engcom-Hotel requested changes
Hello @rvr-robert,

Thanks for the contribution!

Please refer to the below review comment and fix those. Also please look into the failed tests.

Thanks

2024-11-22 11:22 UTC, engcom-Hotel commented on app/code/Magento/PageBuilder/Controller/Adminhtml/ContentType/Block/Metadata.php
> +                        ['eq' => $params['block_id']]
It seems to me a typo, please review this condition `['eq' => $params['block_id']]` is repeating.

2025-01-06 12:02 UTC, engcom-Hotel commented
Hello @rvr-robert,

Have you had a chance to look into this https://github.com/magento/magento2-page-builder/pull/812#pullrequestreview-2454185722?

Thanks

2025-01-21 03:39 UTC, engcom-Hotel commented
Hello @rvr-robert,

We have noticed that this PR has not been updated for a while. Therefore, we are closing it for now.

Please let us know when you are ready to work on it again, and we will be happy to reopen the PR.

Thank you for your valuable contribution!

2025-01-21 03:39 UTC, closed without merging