PageSpeed Insights - Ensure text remains visible during webfont load
magento/magento2-page-builder pull request #834
Opened 2022-11-29 06:37 UTC by kanhaiya5590

### Description (*)

### Task
 https://pagespeed.web.dev/ - [PageSpeed Insights](https://pagespeed.web.dev/)
 
 Performance improvement - after changes result => All text remains visible during Webfont loads

Before changes - Ensure text remains visible during Webfont load
![image](https://user-images.githubusercontent.com/9975788/204456171-6e6fc59a-89be-401b-a99b-86868a075f57.png)

After changes  - All text remains visible during Webfont loads

![image](https://user-images.githubusercontent.com/9975788/204456089-aa89beb6-f7fa-46af-9cf0-252db3b0f9f5.png)

2022-11-29 11:30 UTC, kanhaiya5590 commented
@magento run all tests

2022-11-29 12:36 UTC, kanhaiya5590 commented
**Static Tests** failed in a different place in the code - anyone can help on this as changes have not impacted that.

2023-01-09 12:35 UTC, paras89 commented
HI @kanhaiya5590, as part of the process, need to fix the static test failures in the file that was edited.

2023-06-15 14:08 UTC, bluemwhitew requested changes

2023-06-15 14:08 UTC, bluemwhitew commented on app/code/Magento/PageBuilder/view/frontend/web/css/source/_icons.less
> +        font-display: swap;
Nice one!

Personally, I'd use `font-display: block` in the same way `magento/theme-frontend-blank/web/css/source/_icons.less` implements. Unlike text-based fonts where you're showing _something_ before progressively "swapping" to the designated font, icons don't have anything useful to show.

There's a [CSS Tricks](https://css-tricks.com/hey-hey-font-display) article that still stands up today that does a far better job of explaining than I could hope to (also covers the icon font use case).

In addition, I would recommend adding this to the _top_ with the other `font-*` properties for improved readability.

I don't know why this implementation doesn't use the `.lib-font-face()` wrapper, `font-style` and `font-weight` don't use `@font-style__base` and `@font-weight__regular` accordingly, etc.

2024-05-10 07:25 UTC, engcom-Hotel commented
@magento run all tests

2024-05-10 09:08 UTC, engcom-Hotel commented
We are picking this PR for further development

2024-05-10 11:02 UTC, engcom-Hotel commented
@magento run Static Tests

2024-05-16 06:09 UTC, engcom-Hotel commented
@magento run Static Tests

2024-05-16 07:10 UTC, engcom-Hotel commented
@magento run all tests

2024-05-16 10:02 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2024-05-17 11:24 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2024-05-23 05:44 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2024-05-23 12:23 UTC, engcom-Hotel commented
The Failed tests seem flaky to me. Hence moving this PR in testing

2024-05-23 12:23 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2024-05-27 10:40 UTC, engcom-Bravo commented
Hi @kanhaiya5590,

Thanks for the collaboration & contribution!.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshot.

<img width="958" alt="Screenshot 2024-05-27 at 12 29 32" src="https://github.com/magento/magento2-page-builder/assets/51680745/44e0fc76-5d20-47c1-9f2b-4fda2c82dbf4">


Could you please try to reproduce the issue in Latest 2.4-develop instance and could you please let us know if we are still missing anything.

Thanks.

2024-05-30 05:45 UTC, engcom-Bravo commented
Hi @kanhaiya5590,

We are not able to reproduce the issue.

Can you please confirm the issue still exist on 2.4-develop?

please refer to this https://github.com/magento/magento2-page-builder/pull/834#issuecomment-2133195746

Lets us know if you are still facing the issue on 2.4-develop with detailed steps.

Moving it to `on hold`

Thanks.

2024-06-10 06:39 UTC, engcom-Bravo commented
HI @kanhaiya5590,

Thank you for your contribution!

As mentioned https://github.com/magento/magento2-page-builder/pull/834#issuecomment-2133195746, please have a look and let us know if we are missing anything.

Till then closing this PR. Please feel free to reopen it as you want to update further.

Thank you!

2024-06-10 06:39 UTC, closed without merging