Layout - fallback mechanism Fixed
magento/magento2-page-builder pull request #835
Opened 2022-11-29 06:54 UTC by kanhaiya5590

### Description (*)

### Task

A layout file was added in page_layout so the fallback mechanism not working as expected.

usually, this not identify in normal cases but if we will working on layout updates then this causes concern so fixed and moved the layout file to a valid location.

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#829: layout 2 columns left avoid to override layout on catalog_category_view

2022-11-29 11:27 UTC, kanhaiya5590 commented
CC : @sidolov

2022-11-29 11:28 UTC, kanhaiya5590 commented
@magento run all tests

2024-11-22 13:58 UTC, engcom-Hotel commented
@magento run all tests

2024-11-25 13:16 UTC, engcom-Hotel requested changes
Hello @kanhaiya5590,

Thanks for the contribution!

Please fix the failed automated test.

Thanks

2024-12-04 10:58 UTC, engcom-Hotel commented
@magento run all tests

2024-12-13 10:38 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2024-12-23 03:13 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2024-12-23 11:41 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2024-12-23 14:11 UTC, engcom-Hotel commented
The Functional B2B test seems flaky. The failures are different in last 2 consecutive runs. Please refer to the below screenshots:

_**[Run 1 B2b functional Test](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2-page-builder/pull/835/e12f8832b7ce32e5c9a9613338cd88a7/Functional/allure-report-b2b/index.html#categories/7441e147742cc9294f4ce2a0b5090c42/30ba7e489137b5ce/)**_
![image](https://github.com/user-attachments/assets/0029af42-e41a-4d59-baad-e30bf117ed47)

_**[Run 2 B2b functional Test](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2-page-builder/pull/835/9020c1522ca377d5043eed42b64c76ca/Functional/allure-report-b2b/index.html#categories/3e96a6e800d5b4385a4b71889e926611/8064277aeaebd656/)**_
![image](https://github.com/user-attachments/assets/989d389a-e5ff-4478-9424-8c1b43f74407)

Hence moving this PR in testing.

Thanks

2024-12-23 14:12 UTC, engcom-Hotel approved these changes

2024-12-27 12:14 UTC, engcom-Hotel commented
:x: QA not Passed

## Precondition
Magento Page Builder version >= 1.3.0

## Manual Testing Scenario

1. Create a layout/catalaog_category_view.xml in your theme.
2. Set the attribute layout of the xml-node page to 1column

## Expected Result: :heavy_check_mark:

- Category page has layout one column

## Actual Result: :heavy_multiplication_x:

- Category page has still 2 column layout
![image](https://github.com/user-attachments/assets/5d6d33d3-a0ab-4178-b991-e514d5df26f3)

cc: @antoniocarboni @jasperzeinstra

2025-01-06 12:01 UTC, engcom-Hotel commented
Hello @kanhaiya5590,

Have you had a chance to look into this https://github.com/magento/magento2-page-builder/pull/835#issuecomment-2563644716?

Please let us know if missed anything.

cc: @antoniocarboni @jasperzeinstra

2025-01-21 03:38 UTC, engcom-Hotel commented
Hello @kanhaiya5590,

We have noticed that this PR has not been updated for a while. Therefore, we are closing it for now.

Please let us know when you are ready to work on it again, and we will be happy to reopen the PR.

Thank you for your valuable contribution!

2025-01-21 03:38 UTC, closed without merging