(Video) Calling jarallax-wrapper and loading on demand librairies
magento/magento2-page-builder pull request #865
Opened 2024-02-18 15:49 UTC by Amadeco

I needed to replace jarallax with jarallax-wrapper to make it work with a custom Js bundler  (Magepack Bundle) Indeed, without  jarallax-wrapper, window.jarallax is not populated and return an error (undefined var).

I take advantage to this commit to suggest to load on demand librairies (jarallaxVideo, vimeoWrapper) after the check of the data background-type.

### Description (*)

### Story

### Bug

### Task

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#<issue_number>: Issue title

### Builds

### Related Pull Requests

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-22 11:25 UTC, engcom-Hotel commented
@magento run all tests

2024-11-27 09:46 UTC, engcom-Hotel commented
Hello @Amadeco,

Thanks for the contribution!

We request you to please provide us with some more details on the replacement of `jarallax` with `jarallax-wrapper`. We can pick this PR as a `feature request`. But we need this information to proceed.

Thanks

2024-11-27 10:36 UTC, Amadeco commented
Hello,

At the time, I was using a bundler for production ([https://github.com/magesuite/magepack](https://github.com/magesuite/magepack)) to manage JavaScript files. This issue is isolated to that setup.

When I compiled the files, the jarallax object was not defined, likely due to a context issue or the way the bundler handles modules (specifically, the order of the JS files).

Magento provide the _jarallax-wrapper_ module to call the _jarallax_ class and attach it to the _window_ (global) object, which is why I submitted this issue in the first place to solve mine.

But the ways the requirejs-config file is declared (shim), Magento_PageBuilder/js/resource/jarallax/jarallax-video would be sufficient :

```
shim: {
    'Magento_PageBuilder/js/resource/jarallax/jarallax-video': {
        deps: ['jarallax-wrapper', 'vimeoWrapper']
    }
}
```

(it would be great to load vimeoWrapper and vimeo only on demand too)

Nowadays, with HTTP/2 and HTTP/3, bundlers are not always ideal for frontend performance which generate big JS files. It's up to you to decide whether addressing this is still relevant.

2024-11-28 10:13 UTC, engcom-Hotel commented
@magento create issue

2024-11-28 10:24 UTC, engcom-Hotel commented
Hello @Amadeco,

Thanks for the detailed explanations!

It seems the issue occurs due to the third-party extension i.e. https://github.com/magesuite/magepack not from the core Magento 2. We request you to please use the default Magento's JS Bundler:

https://developer.adobe.com/commerce/frontend-core/guide/themes/js-bundling/

And let us know if you are still able to reproduce the issue.

Thanks

2024-11-28 10:24 UTC, engcom-Hotel requested changes
Hello @Amadeco,

Thanks for the detailed explanations!

It seems the issue occurs due to the third-party extension i.e. https://github.com/magesuite/magepack not from the core Magento 2. We request you to please use the default Magento's JS Bundler:

https://developer.adobe.com/commerce/frontend-core/guide/themes/js-bundling/

And let us know if you are still able to reproduce the issue.

Thanks

2024-12-03 12:14 UTC, engcom-Hotel commented
Hello @Amadeco,

Have you had a chance to look into this https://github.com/magento/magento2-page-builder/pull/865#pullrequestreview-2467582905?

Thanks

2025-01-06 11:59 UTC, engcom-Hotel commented
Hello @Amadeco,

We have noticed that this PR has not been updated for a while. Therefore, we are closing it for now.

Please let us know when you are ready to work on it again, and we will be happy to reopen the PR.

Thank you for your valuable contribution!

2025-01-06 11:59 UTC, closed without merging