magento/magento2-page-builder#866: Add element existence check to prevent Page Builder editor crashes
magento/magento2-page-builder pull request #873
Opened 2024-08-30 15:27 UTC by artttj

### Description

We encountered a scenario where missing HTML elements in Page Builder led to runtime errors due to direct calls to `setAttribute`.

To address this, we added an existence check before setting attributes. This change prevents the editor from breaking and improves stability by handling cases where elements are missing.

Ideally, the core should include such checks to enhance overall resilience and user experience.

### Story
N/A

### Bug
N/A

### Task
N/A

### Fixed Issues

1. magento/magento2-page-builder#866: Graceful Handling of Null element in Page Builder to Prevent Editor Failure

### Builds

### Related Pull Requests

### Manual Testing Scenarios

Please test the following scenarios to verify the changes:

1. **Remove `data-pb-style` Attribute**:
   - Remove the `data-pb-style` attribute from an element with applied styles.
   - Ensure the Page Builder continues to work without issues.

2. **Modify `data-pb-style` Hash**:
   - Change the `data-pb-style` attribute's value to a non-relevant hash.
   - Confirm that the Page Builder handles this gracefully and remains functional.

3. **Remove HTML Element**:
   - Delete the HTML element to which styles are applied.
   - Check that the Page Builder does not crash and continues to operate normally.

**Note**: This issue was observed when using the DeepL API, but similar problems might occur in other scenarios. The preview editor should remain stable.

### Questions or comments
N/A

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-08-30 15:29 UTC, artttj commented
@magento run all tests

2024-10-21 10:19 UTC, engcom-Hotel commented
@magento run all tests

2024-10-21 12:29 UTC, engcom-Hotel requested changes
Hello @artttj,

Thanks for the contribution!

The PR changes seems good to me, but please cover the changes with some automated test in accordance of [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

2024-10-25 11:15 UTC, engcom-Hotel commented
After discussing it internally, it was found that the automated test is not required for this change. Hence moving it to ready for testing.

Thanks

2024-10-25 12:06 UTC, engcom-Hotel commented
Hello @artttj,

Thanks for the contribution!

:x: QA not Passed

We have tried to reproduce the actual issue in the 2.4-develop branch with pagebuilder's develop branch, but the issue is not reproducible for us. Please refer to the below screencast for reference:

https://github.com/user-attachments/assets/38e9a8ff-1cca-42c4-9bba-6856b17995f1

Let us know if we missed anything.

Thanks

2024-11-11 12:38 UTC, engcom-Hotel commented
Hello @artttj,

This PR is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new PR.

Thanks

2024-11-11 12:38 UTC, closed without merging