Update HtmlFilter.php DOM Text Interpreted As HTML
magento/magento2-page-builder pull request #879
Opened 2024-12-19 03:11 UTC by Shivam7-1

Description
Here innerText can be used it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-19 03:13 UTC, Shivam7-1 commented
Hii @engcom-Hotel Could You Please Take a look and Review Here in this PR ?
Thanks

2024-12-19 08:52 UTC, Shivam7-1 commented
@magento run all tests

2025-01-06 11:34 UTC, engcom-Hotel requested changes
Hello @Shivam7-1,

Please refer to the below review comment.

Thanks

2025-01-06 11:34 UTC, engcom-Hotel commented on app/code/Magento/PageBuilder/Model/Stage/HtmlFilter.php
> +        $innerText = '';
Please elaborate on the purpose of this change. 

Also as I can see here you are just changing the variable name. If that is so then please update the same in line number 115 and 118:

https://github.com/magento/magento2-page-builder/blob/1a52ef4c5fe7dc2daf8504f6e701ad64011c6457/app/code/Magento/PageBuilder/Model/Stage/HtmlFilter.php#L115

https://github.com/magento/magento2-page-builder/blob/1a52ef4c5fe7dc2daf8504f6e701ad64011c6457/app/code/Magento/PageBuilder/Model/Stage/HtmlFilter.php#L118

2025-01-06 11:41 UTC, Shivam7-1 commented on app/code/Magento/PageBuilder/Model/Stage/HtmlFilter.php
> +        $innerText = '';
Hii @engcom-Hotel  Thanks For Reviewing Yes done this changes

2025-01-06 11:50 UTC, engcom-Hotel requested changes

2025-01-06 11:50 UTC, engcom-Hotel commented on app/code/Magento/PageBuilder/Model/Stage/HtmlFilter.php
> +        $innerText = '';
Also please help us with the purpose of this PR. In the actual codebase we are not using the `innerHTML` property, here `$innerHTML` is used as a variable. So this change doesn’t make any sense to me.

Please correct me if I am wrong.

2025-01-07 06:00 UTC, Shivam7-1 commented
Hii @engcom-Hotel Thank you for the feedback. You’re correct that `$innerHTML` is just a variable and not the `innerHTML` property.  I got Confused here by the name so it's not required here I think

2025-01-08 06:38 UTC, engcom-Hotel commented
Thanks @Shivam7-1, We are closing this PR as per your [last comment](https://github.com/magento/magento2-page-builder/pull/879#issuecomment-2574452660).

2025-01-08 06:38 UTC, closed without merging